[workspace]
members = [".", "ipld/resolver"]

[workspace.package]
authors = ["Protocol Labs"]
edition = "2021"
license-file = "LICENSE"

[package]
name = "ipc_agent"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
async-channel = "1.8.0"
async-trait = "0.1.61"
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
indoc = "2.0.0"
log = "0.4.17"
reqwest = { version = "0.11.13", features = ["json"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
cid = { version = "0.8.3", default-features = false, features = ["serde-codec"] }
tokio = { version = "1.16", features = ["full"] }
tokio-tungstenite = { version = "0.18.0", features = ["native-tls"] }
derive_builder = "0.12.0"
num-traits = "0.2.15"
env_logger = "0.10.0"
base64 = "0.21.0"
strum = { version = "0.24", features = ["derive"] }
toml = "0.7.2"
url = { version = "2.3.1", features = ["serde"] }
warp = "0.3.3"
bytes = "1.4.0"
clap = { version = "4.1.4", features = ["env", "derive"] }
thiserror = "1.0.38"

fvm_shared = { workspace = true }
fil_actors_runtime = { workspace = true }
ipc-sdk = { workspace = true }
ipc-subnet-actor = { workspace = true }
ipc-gateway = { workspace = true }

[workspace.dependencies]
fvm_shared = { version = "=3.0.0-alpha.17", default-features = false }
fil_actors_runtime = { git = "https://github.com/consensus-shipyard/fvm-utils", features = ["fil-actor"] }
ipc-sdk = { git = "https://github.com/consensus-shipyard/ipc-actors.git" }
ipc-subnet-actor = { git = "https://github.com/consensus-shipyard/ipc-actors.git", features = [] }
ipc-gateway = { git = "https://github.com/consensus-shipyard/ipc-actors.git", features = [] }
