[package]
name = "ipc_ipld_resolver"
description = "P2P library to resolve IPLD content across IPC subnets."
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
blake2b_simd = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
libp2p = { version = "0.50", default-features = false, features = [
  "gossipsub",
  "kad",
  "identify",
  "ping",
  "noise",
  "yamux",
  "tcp",
  "dns",
  "mplex",
  "request-response",
  "metrics",
  "tokio",
  "macros",
  "serde",
  "secp256k1",
] }
libp2p-bitswap = "0.25"
libipld = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
quickcheck = { workspace = true, optional = true }

ipc-sdk = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_shared = { workspace = true, optional = true }

[dev-dependencies]
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }
fvm_shared = { workspace = true, features = ["arb"] }


[features]
default = ["arb"]
arb = ["quickcheck", "fvm_shared/arb"]
