[package]
name = "ipc_ipld_resolver"
description = "P2P library to resolve IPLD content across IPC subnets."
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
blake2b_simd = { workspace = true }
bloom = "0.3"
gcra = "0.3"
lazy_static = { workspace = true }
libp2p = { version = "0.50", default-features = false, features = [
  "gossipsub",
  "kad",
  "identify",
  "ping",
  "noise",
  "yamux",
  "tcp",
  "dns",
  "mplex",
  "request-response",
  "metrics",
  "tokio",
  "macros",
  "serde",
  "secp256k1",
  "plaintext",
] }
libipld = { workspace = true }
log = { workspace = true }
prometheus = { workspace = true }
quickcheck = { workspace = true, optional = true }
rand = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

ipc-sdk = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_shared = { workspace = true, optional = true }
fvm_ipld_blockstore = { workspace = true, optional = true }

# Using a fork of libp2p-bitswap so that we can do rate limiting.
#libp2p-bitswap = "0.25"
libp2p-bitswap = { git = "https://github.com/consensus-shipyard/libp2p-bitswap", branch = "req-res-pub" }

[dev-dependencies]
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }
env_logger = { workspace = true }
fvm_shared = { workspace = true, features = ["arb"] }
fvm_ipld_hamt = "0.6"

[features]
default = ["arb", "missing_blocks"]
arb = ["quickcheck", "fvm_shared/arb"]
missing_blocks = ["fvm_ipld_blockstore"]
