[subnets]

[subnets.root]
path = "/root"
rpc_api = "https://example.org/rpc/v0"
auth_token = "token_root"

[subnets.child]
path = "/root/f3thgjtvoi65yzdcoifgqh6utjbaod3ukidxrx34heu34d6avx6z7r5766t5jqt42a44ehzcnw3u5ehz47n42a"
rpc_api = "https://example.org/rpc/v0"
auth_token = "token_child"
accounts = ["f3thgjtvoi65yzdcoifgqh6utjbaod3ukidxrx34heu34d6avx6z7r5766t5jqt42a44ehzcnw3u5ehz47n42a"]
